extends Node

const CODE_BLOCKS = preload("res://CodeBlocks/CodeBlocks.gd").CodeBlockID

enum WorldCharacters {KING, ORACLE, GUARD, CAT, BARON, ENEMY}

const ACCEPTS = [
	[CODE_BLOCKS.SWORD, CODE_BLOCKS.TIMID_SCOUT, CODE_BLOCKS.CONFIDENT_SCOUT, CODE_BLOCKS.HADAMARD],
	[CODE_BLOCKS.SWORD, CODE_BLOCKS.TIMID_SCOUT, CODE_BLOCKS.CONFIDENT_SCOUT, CODE_BLOCKS.HADAMARD, CODE_BLOCKS.CONSULT_ORACLE],
	[CODE_BLOCKS.SWORD, CODE_BLOCKS.TIMID_SCOUT, CODE_BLOCKS.CONFIDENT_SCOUT, CODE_BLOCKS.HADAMARD],
	[CODE_BLOCKS.SWORD, CODE_BLOCKS.TIMID_SCOUT, CODE_BLOCKS.CONFIDENT_SCOUT, CODE_BLOCKS.HADAMARD],
	[CODE_BLOCKS.SWORD, CODE_BLOCKS.TIMID_SCOUT, CODE_BLOCKS.CONFIDENT_SCOUT, CODE_BLOCKS.HADAMARD],
	[CODE_BLOCKS.SWORD, CODE_BLOCKS.TIMID_SCOUT, CODE_BLOCKS.CONFIDENT_SCOUT, CODE_BLOCKS.HADAMARD]
]

const ICONS = [
	preload("res://CodingUI/CodeArea/Headers/KingIcon.tscn"),
	preload("res://CodingUI/CodeArea/Headers/KingIcon.tscn"),
	preload("res://CodingUI/CodeArea/Headers/GuardIcon.tscn"),
	preload("res://CodingUI/CodeArea/Headers/CatIcon.tscn"),
	preload("res://CodingUI/CodeArea/Headers/BaronIcon.tscn"),
	preload("res://CodingUI/CodeArea/Headers/EnemyIcon.tscn")
]